from pptx import Presentation
from pptx.util import Inches
import os

def create_ppt_with_image(image_paths, output_path, title="Kaavalar AI Presentation"):
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_item = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_item.text = title
    subtitle.text = "Generated by Kaavalar AI Guardian"

    # Add images to slides
    for img_path in image_paths:
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        # Add title to slide
        title_shape = slide.shapes.title
        title_shape.text = os.path.basename(img_path)
        
        # Add image
        # Center the image roughly
        left = Inches(1)
        top = Inches(1.5)
        height = Inches(5)
        slide.shapes.add_picture(img_path, left, top, height=height)
        
    prs.save(output_path)
    return output_path

def add_text_to_ppt(input_path, output_path, text_to_add):
    if os.path.exists(input_path):
        prs = Presentation(input_path)
    else:
        prs = Presentation()
        
    blank_slide_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_slide_layout)
    
    left = top = width = height = Inches(1)
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.text = text_to_add
    
    prs.save(output_path)
    return output_path
